// Do not edit this file; automatically generated by build.py.
"use strict";
document.write('<script type="text/javascript" src="closure-library/closure/goog/base.js"></script>');
(function() {
  var filenames = ['core/blockly.js', 'core/block.js', 'core/block_svg.js', 'core/bubble.js', 'core/comment.js', 'core/connection.js', 'core/contextmenu.js', 'core/field.js', 'core/field_dropdown.js', 'core/field_checkbox.js', 'core/field_colour.js', 'core/field_image.js', 'core/field_label.js', 'core/field_textinput.js', 'core/field_variable.js', 'core/flyout.js', 'core/generator.js', 'core/inject.js', 'core/input.js', 'core/mutator.js', 'core/names.js', 'core/procedures.js', 'core/scrollbar.js', 'core/toolbox.js', 'core/tooltip.js', 'core/trashcan.js', 'core/utils.js', 'core/variables.js', 'core/warning.js', 'core/workspace.js', 'core/xml.js'];
  for (var x = 0; x < filenames.length; x++) {
    document.write('<script type="text/javascript" src="' + filenames[x] + '"></script>');
  }
})();
